// Generated by github.com/davyxu/PhotonSharp
// DO NOT EDIT!!
using Photon;
using System;

namespace UnitTest
{
	[NativeWrapperClass(typeof(DataStackBalanceTest))]
	public class DataStackBalanceTestWrapper
	{
		[NativeEntry(NativeEntryType.StaticFunc)]
		public static int native_less( VMachine vm )
		{
			var phoRetArg = DataStackBalanceTest.native_less(  );

			vm.DataStack.PushInteger32( phoRetArg );
			
			return 1;
		}
		
		[NativeEntry(NativeEntryType.StaticFunc)]
		public static int native_more( VMachine vm )
		{
			Int32 out1 = default(Int32);
			Int32 out2 = default(Int32);
			Int32 out3 = default(Int32);
			DataStackBalanceTest.native_more( out out1, out out2, out out3 );

			vm.DataStack.PushInteger32( out1 );
			vm.DataStack.PushInteger32( out2 );
			vm.DataStack.PushInteger32( out3 );
			
			return 3;
		}
		
	}
}
