// Generated by github.com/davyxu/PhotonSharp
// DO NOT EDIT!!
using Photon;
using System;

namespace PhotonCompiler
{
	[NativeWrapperClass(typeof(DataStackBalanceTest))]
	public class DataStackBalanceTestWrapper
	{
		[NativeEntry(NativeEntryType.StaticFunc)]
		public static int native_less( VMachine vm )
		{
			var phoRetArg = DataStackBalanceTest.native_less(  );

			vm.DataStack.PushInteger32( phoRetArg );
			
			return 1;
		}
		
		[NativeEntry(NativeEntryType.StaticFunc)]
		public static int native_more( VMachine vm )
		{
			Int32 out1;
			Int32 out2;
			DataStackBalanceTest.native_more( out out1, out out2 );

			vm.DataStack.PushInteger32( out1 );
			vm.DataStack.PushInteger32( out2 );
			
			return 2;
		}
		
	}
}
