// Generated by github.com/davyxu/PhotonSharp
// DO NOT EDIT!!
using Photon;
using System;

namespace UnitTest
{
	[NativeWrapperClass(typeof(NativeClass))]
	public class NativeClassWrapper
	{		
		[NativeEntry(NativeEntryType.ClassMethod)]
		public static int outAsRetValue( VMachine vm )
		{
			var phoClassIns = vm.DataStack.GetNativeInstance<NativeClass>(0);
			
			var a = vm.DataStack.GetInteger32(1);
			var c = vm.DataStack.GetString(2);
			
			Int32 b = default(Int32);
			var phoRetArg = phoClassIns.outAsRetValue( a, c, out b );

			vm.DataStack.PushInteger32( b );
			vm.DataStack.PushString( phoRetArg );
			
			return 2;
		}


        [NativeEntry(NativeEntryType.Property)]
        public static void MyProp(object phoIns, ref object value, bool isGet )
        {
            var phoClassIns = phoIns as NativeClass;

            if (isGet)
            {
                VMachine.String2Value(phoClassIns.MyProp);
            }
            else
            {
                phoClassIns.MyProp = VMachine.Value2String(value);
            }
        }
		
		[NativeEntry(NativeEntryType.ClassMethod)]
		public static int foo( VMachine vm )
		{
			var phoClassIns = vm.DataStack.GetNativeInstance<NativeClass>(0);
			
			var a = vm.DataStack.GetInteger32(1);
			
			var phoRetArg = phoClassIns.foo( a );

			vm.DataStack.PushString( phoRetArg );
			
			return 1;
		}
		
	}
}
